#!/bin/sh
#
# This should get pulled into the BOM for EQAE20 and general configure from zbrew
#
if ! [ $# -eq 2 ]; then
	echo "Syntax: configregistration ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
if [ -z "${PRODUCT_CODE}" ]; then
	echo "configregistration requires a productcode, which should be specified in the JSON ORDER for EQAE20" >&2
	exit 8
fi

verb="$1"
script="$2"
zbrew=`whence zbrew`
zbrewdir=${zbrew%/*}
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export PRODUCT_CODE="${PRODUCT_CODE}"
export PRODUCT_NAME="${PRODUCT_NAME}"
export FEATURE_NAME="${FEATURE_NAME}"
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv

enablementText="PRODUCT OWNER('IBM CORP')
	NAME('\${PRODUCT_NAME}')
	ID(\${PRODUCT_CODE})
	VERSION(*) RELEASE(*) MOD(*)
	FEATURENAME('\${FEATURE_NAME}')
	STATE(ENABLED)"

swregistrar "eqae20" "${verb}" "\${PRODUCT_CODE}" "\${enablementText}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
