#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: registration ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
export PRODUCT_CODE="${PRODUCT_CODE}"
. zbrewsetenv
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs

datasets="\${ZBREW_TGT_HLQ}EQAE20.SEQAAUTH"
if \`supportsMFI "\$PRODUCT_CODE"\`; then
	datasets="\${datasets} \${ZBREW_TGT_HLQ}EQAE20.SEQABMOD"
fi

apfregistrar eqae20 "${verb}" "\${datasets}"
exit \$?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
