#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: ivp ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
	#!/bin/sh
	#set -x
	export PATH=${zbrewdir}:\$PATH
	. zbrewsetenv
EOF

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >>${script}
	# No code required to 'undo' IVP
	exit 0
EOF

else # ENABLE
	cat << EOF >>${script}
	\${ZBREW_WORKROOT}/zbrew-eqa/eqae20/update/ivp
	exit \$?
EOF

fi

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
