#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: ivp ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >${script}
#!/bin/sh
# No code required to 'undo' IVP
exit 0
EOF
	exit 0
fi

# ENABLE

cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv

\${ZBREW_WORKROOT}/zbrew-eqa/eqae20/update/ivp
exit $?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
