#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: authlla ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >${script}
#!/bin/sh
export PRODUCT_CODE="${PRODUCT_CODE}"
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv eqae20
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs

if ! \`supportsMFI "\$PRODUCT_CODE"\`; then
	# Not applicable for these products
	exit 0
fi
llregistrar eqae20 disable "\${ZBREW_TGT_HLQ}EQAE20.SEQABMOD"

exit $?
EOF
	chmod u+x "${script}"
	exit 0
fi

#
# ENABLE
#
cat << EOF >${script}
#!/bin/sh
#set -x

export PATH=${zbrewdir}:\$PATH
. zbrewsetenv eqae20
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs
export PRODUCT_CODE="${PRODUCT_CODE}"

if ! \`supportsMFI "\$PRODUCT_CODE"\`; then
	# Not applicable for these products
	exit 0
fi

# Module is APF authorized in the APF authorization step
llregistrar eqae20 enable "\${ZBREW_TGT_HLQ}EQAE20.SEQABMOD"

exit \$?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
