#!/bin/sh
#set -x

if ! [ $# -eq 2 ]; then
	echo "Syntax: dbgmgr_security ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv eqae20
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs
export PRODUCT_CODE="$PRODUCT_CODE"

if ! \`supportsDebugManager "\$PRODUCT_CODE"\`; then
	exit 0
fi
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"

if [ "${verb}" = "DISABLE" ]; then
cat << EOF >>${script}
	#MSF TBD
EOF

else
cat << EOF >>${script}
	if \`undefinedProperty "\${EQAE20_DBGMGR_CLIENT}"\` ; then
		echo "dbgmgr_security: EQAE20_DBGMGR_CLIENT must be specified" >&2
		exit 4
	fi
	if \`undefinedProperty "\${EQAE20_DBGMGR_HOST}"\` ; then
		echo "dbgmgr_security: EQAE20_DBGMGR_HOST must be specified" >&2
		exit 4
	fi

	ttlsrule="
	TTLSRule zOS_Debugger_Debug_Manager  
	{
	  LocalPortRange      \${EQAE20_DBGMGR_CLIENT}
	  Direction           Inbound
	  TTLSGroupActionRef  act_zOS_Debugger_Debug_Manager
	}
	TTLSEnvironmentAction  act_zOS_Debugger_Debug_Manager
	{
	  HandshakeRole Server
	  TTLSKeyRingParms
	  {
	    Keyring dbgmgr_security.racf # Keyring must be owned by the Debug Manager
	  }
	}
	TTLSGroupAction grp_Production
	{
	  TTLSEnabled On
	  Trace       2
	}"

#	echo "\$ttlsrule"

	# msf - for ADCD, this is where the profile lives export TCPIP_PROFILE="ADCD.Z24A.TCPPARMS(PROF2)"

	ttlsresult=\`opercmd 'd tcpip,,netstat,config' | awk ' /TTLS:/ { print \$2; }'\`
	pagentresult=\`opercmd 'd tcpip,,netstat,config' | awk ' /PROCNAME: PAGENT/ { print; }'\`

	if ! [ "\${ttlsresult}" = 'YES' ] ; then
		ttlsentry="TCPCONFIG TTLS           ; Required for AT-TLS
"
	else
		ttlsentry=''
	fi
	if [ "\${pagentresult}" = '' ]; then
		pagententry="AUTOLOG
  PAGENT                 ; POLICY AGENT, required for AT-TLS
ENDAUTOLOG"
	else
		pagententry=''
	fi
	if [ "\${ttlsentry}" != '' ] || [ "\${pagententry}" != '' ]; then
		text="\${ttlsentry}\${pagententry}"	
		hdr="; EQAE20 start ;"
		ftr="; EQAE20 end ;"
		registrar "EQAE20" "ENABLE" "ZBREW.TCPIP" "PROFILE" "\$hdr" "\$ftr" ";" ";" "\${text}"
		rc=\$?
		if [ \$rc -gt 0 ]; then
			exit \$rc
		fi
	fi
	exit 0
EOF
fi

exit 0
