#!/bin/sh
#set -x

if ! [ $# -eq 2 ]; then
	echo "Syntax: dbgmgr_saf ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv eqae20
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs
export PRODUCT_CODE="$PRODUCT_CODE"

if ! \`supportsDebugManager "\$PRODUCT_CODE"\`; then
	exit 0
fi
sp=\`securityProduct\`
if [ "\${sp}" != "RACF" ]; then
	echo "Security product support for \${sp} not implemented yet" >&2
	exit 16
fi

EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >>${script}

	tsocmd "PERMIT BPX.SERVER CLASS(FACILITY) DELETE ID(STCDBM)" >/dev/null 2>/dev/null
	tsocmd "RDELETE STARTED DBGMGR.*" >/dev/null 2>&1
	tsocmd "DELUSER STCDBM" >/dev/null 2>&1
	issueTSO "SETROPTS RACLIST(FACILITY) REFRESH"
	chk "\$?" "Unable to refresh facility task class"
	exit 0
EOF

else 
	cat << EOF >>${script}
	issueTSO "SETROPTS GENERIC(FACILITY)"
	chk "\$?" "Unable to set generic(facility)"

	issueTSO "SETROPTS CLASSACT(FACILITY) RACLIST(FACILITY)"
	chk "\$?" "Unable to set classact(facility)"

	issueTSO "SETROPTS GENERIC(STARTED)"
	chk "\$?" "Unable to set generic(started)"

	issueTSO "SETROPTS CLASSACT(STARTED) RACLIST(STARTED)"
	chk "\$?" "Unable to activate STARTED class"

	if ! \`racfGroupExists STCGROUP\` ; then
		issueTSO "RDEFINE STARTED ** STDATA(USER(=MEMBER) GROUP(STCGROUP) TRACE(YES))"
		chk "\$?" "Unable to define STCGROUP"

		issueTSO "ADDGROUP STCGROUP OMVS(AUTOGID) DATA('GROUP WITH OMVS SEGMENT FOR STARTED TASKS')"
		chk "\$?" "Unable to add group with OMVS segment for started tasks"
	fi

	tsocmd "DELUSER STCDBM" >/dev/null 2>&1
	issueTSO "ADDUSER STCDBM DFLTGRP(STCGROUP) NOPASSWORD NAME('DEBUG MANAGER') OMVS(AUTOUID HOME(/tmp) PROGRAM(/bin/sh) ) DATA('IBM z/OS Debugger')"
	chk "\$?" "Unable to create user STCDBM"

	tsocmd "RDELETE STARTED DBGMGR.*" >/dev/null 2>&1
	issueTSO "RDEFINE STARTED DBGMGR.* DATA('DEBUG MANAGER') STDATA(USER(STCDBM) GROUP(STCGROUP) TRUSTED(NO))"
	chk "\$?" "Unable to define started task profile DBGMGR.*"

	tsocmd "DELUSER STCDBM" >/dev/null 2>&1
	issueTSO "ADDUSER PAGENT DFLTGRP(SYS1) OMVS(UID(0) SHARED HOME('/')) NAME('TCP/IP POLICY AGENT') NOPASSWORD"
	chk "\$?" "Unable to create user PAGENT"

	tsocmd "RDELETE STARTED PAGENT.*" >/dev/null 2>&1
	issueTSO "RDEFINE STARTED PAGENT.* STDATA(USER(PAGENT) GROUP(SYS1)) DATA('TCP/IP POLICY AGENT')
	chk "\$?" "Unable to define started task profile PAGENT.*"

	issueTSO "SETROPTS RACLIST(STARTED) REFRESH"
	chk "\$?" "Unable to refresh started task class"

	if ! \`racfProfileExists "FACILITY" "BPX.SERVER"\` ; then
		issueTSO "RDEFINE FACILITY BPX.SERVER UACC(NONE)"
		chk "\$?" "Unable to define profile BPX.SERVER"
	fi

	if ! \`racfProfileExists "OPERCMDS" "MVS.SERVMGR.PAGENT"\` ; then
		issueTSO "RDEFINE OPERCMDS MVS.SERVMGR.PAGENT UACC(NONE) DATA('restrict startup of policy agent')"
		chk "\$?" "Unable to define profile MVS.SERVMGR.PAGENT"
	fi

	tsocmd "PERMIT BPX.SERVER CLASS(FACILITY) DELETE ID(STCDBM)" >/dev/null 2>/dev/null
	issueTSO "PERMIT BPX.SERVER CLASS(FACILITY) ACCESS(UPDATE) ID(STCDBM)"
	chk "\$?" "Unable to permit BPX.SERVER ID(STCDBM)"

	tsocmd "PERMIT MVS.SERVMGR.PAGENT(OPERCMDS) DELETE ID(PAGENT)" >/dev/null 2>/dev/null
	issueTSO "PERMIT MVS.SERVMGR.PAGENT CLASS(OPERCMDS) ACCESS(CONTROL) ID(PAGENT)"
	chk "\$?" "Unable to permit MVS.SERVMGR.PAGENT ID(PAGENT)"

	issueTSO "SETROPTS RACLIST(FACILITY) REFRESH"
	chk "\$?" "Unable to refresh facility task class"

	issueTSO "SETROPTS RACLIST(OPERCMDS) REFRESH"
	chk "\$?" "Unable to refresh opercmds class"

	issueTSO "SETROPTS GENERIC(SERVAUTH)"
	chk "\$?" "Unable to set generic(servauth)"

	issueTSO "SETROPTS CLASSACT(SERVAUTH) RACLIST(SERVAUTH)"
	chk "\$?" "Unable to set classact(servauth)"

	tsocmd "RDELETE SERVAUTH EZB.INITSTACK.**" >/dev/null 2>&1
	issueTSO "RDEFINE SERVAUTH EZB.INITSTACK.** UACC(NONE)"
	chk "\$?" "Unable to define servauth profile EZB.INITSTACK.**"

	tsocmd "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) DELETE ID(PAGENT)" >/dev/null 2>/dev/null
	tsocmd "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) DELETE ID(OMPROUTE)" >/dev/null 2>/dev/null
	tsocmd "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) DELETE ID(OSNMPD)" >/dev/null 2>/dev/null
	tsocmd "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) DELETE ID(IOBSNMP)" >/dev/null 2>/dev/null
	tsocmd "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) DELETE ID(NAMED)" >/dev/null 2>/dev/null

	issueTSO "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) ACCESS(READ) ID(PAGENT)"
	chk "\$?" "Unable to permit EZB.INITSTACK ID(PAGENT)"

	issueTSO "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) ACCESS(READ) ID(OMPROUTE)"
	chk "\$?" "Unable to permit EZB.INITSTACK ID(OMPROUTE)"

	issueTSO "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) ACCESS(READ) ID(OSNMPD)"
	chk "\$?" "Unable to permit EZB.INITSTACK ID(OSNMPD)"

	issueTSO "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) ACCESS(READ) ID(IOBSNMP)"
	chk "\$?" "Unable to permit EZB.INITSTACK ID(IOBSNMP)"

	issueTSO "PERMIT EZB.INITSTACK.** CLASS(SERVAUTH) ACCESS(READ) ID(NAMED)
	chk "\$?" "Unable to permit EZB.INITSTACK ID(NAMED)"

	issueTSO "SETROPTS RACLIST(SERVAUTH) REFRESH"
	chk "\$?" "Unable to refresh servauth class"

	issueTSO "SETROPTS RACLIST(OPERCMDS) REFRESH"
	chk "\$?" "Unable to refresh opercmds class"

	if ! \`racfProfileExists "FACILITY" "IRR.DIGTCERT.LIST"\` ; then
		issueTSO "RDEFINE FACILITY IRR.DIGTCERT.LIST UACC(NONE)"
		chk "\$?" "Unable to define profile IRR.DIGTCERT.LIST"
	fi
	if ! \`racfProfileExists "FACILITY" "IRR.DIGTCERT.LISTRING"\` ; then
		issueTSO "RDEFINE FACILITY IRR.DIGTCERT.LISTRING UACC(NONE)"
		chk "\$?" "Unable to define profile IRR.DIGTCERT.LISTRING"
	fi


"
	exit 0
EOF
fi

exit 0
