#!/bin/sh
#set -x

if ! [ $# -eq 2 ]; then
	echo "Syntax: cics ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv eqae20
. \$ZBREW_WORKROOT/zbrew-eqa/eqafuncs
if ! \`supportsCICS \`; then
	exit 0
fi
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >>${script}
	procregistrar eqae20 disable \${ZBREW_DFH_PROC}
	chk "\$?" "Unable to configure EQAE20"
	ccsdregistrar eqae20 disable
	chk "\$?" "Unable to configure EQAE20"
	exit 0
EOF

else 

	cat << EOF >>${script}
	#
	# Stop CICS started task
	# Register the Debug CCSD 
	# Add the debugger modules to the DFHRPL concatenation
	# Update the CICS SYSIN to include the CICS grouplist 
	# Restart the updated started task with the changed JCL/SYSIN
	#

	#
	# Stop CICS region to make changes to it
	#
	stopCICS "\${ZBREW_DFH_PROC}"
	chk "\$?" "Unable to stop CICS region \${ZBREW_DFH_PROC}"

	#
	# remove the ADD GROUP line at the end of the CCSD sample, but keep everything else and register the Debug CCSD
	# 
	ccsd=\`cat "//'\${ZBREW_TGT_HLQ}EQAE20.SEQASAMP(EQACCSD)'" | awk ' /[ ]*ADD[ ]+GROUP/ { print "*"; next; } // {print}'\`
	ccsdregistrar eqae20 ${verb} "\${ccsd}"
	chk "\$?" "Unable to configure EQAE20"

	#
	# Set up the VSAM dataset for DTCN Debugging profiles
	#
	drm -f "\${EQAE20_DTCNPROF}"
	idcamsout="/tmp/eqae20.cicsdtcn.vsam.\$\$.out"
	touch \$idcamsout
	idcamsin="
         DEFINE CLUSTER (RECORDS(256) -
          NAME (\${EQAE20_DTCNPROF}) -
          SHAREOPTIONS(2 3) -                                              
          LOG(NONE) -                                                      
          IXD)             -
         DATA -                                                            
          (RECSZ(2000,2000) -                                              
          NAME (\${EQAE20_DTCNPROF}.DATA) -                           
          KEYS(8 16) -
          FREESPACE(10 10) -
          BUFFERSPACE (20000)) -
         INDEX -
          (NAME(\${EQAE20_DTCNPROF}.INDX))"
	echo "\${idcamsin}" | mvscmdauth --pgm=IDCAMS --sysprint="\${idcamsout}" --sysin=stdin
	rc=\$?
	if [ \$rc -gt 0 ]; then
		echo "Unable to allocate DTCN VSAM dataset for CICS." >&2
		cat "\${idcamsout}"
		rm -f "\${idcamsout}"
		exit \$rc
	fi
	rm -f "\${idcamsout}"

	#
	# update the JCL to include Debug datasets
	# 
	jcl=\`cat "//'\${ZBREW_DFH_PROCLIB}(\${ZBREW_DFH_PROC})'"\`
	chk "\$?" "Unable to add \${ZBREW_TGT_HLQ}EQAE20.SEQAMOD to CICS proclib \${ZBREW_DFH_PROCLIB}(\${ZBREW_DFH_PROC})"

	step=\`echo "\${jcl}" | awk '/\/\/[A-Z0-9\\$#@]+[ ]+EXEC[ ]+PGM=DFHSIP/ { print substr(\$1,3) }'\`
	chk "\$?" "JCL \${ZBREW_DFH_PROCLIB}(\${ZBREW_DFH_PROC}) does not invoke CICS program DFHSIP" 

	jcl=\`jclAddDatasetToDD "\${jcl}" "\${step}" "DFHRPL" "\${ZBREW_TGT_HLQ}EQAE20.SEQAMOD"\`
	chk "\$?" "Unable to add \${ZBREW_TGT_HLQ}EQAE20.SEQAMOD to CICS started task \${ZBREW_DFH_PROCLIB}(\${ZBREW_DFH_PROC})"

	jcl=\`jclReplaceDD "\${jcl}" "\${step}" "SYSIN" "\${ZBREW_TGT_HLQ}SYSIN(\${ZBREW_DFH_SYSIN_TRAN_JCL})"\`
	chk "\$?" "Unable to change CICS SYSIN for \${ZBREW_DFH_PROC} to \${ZBREW_TGT_HLQ}SYSIN(\${ZBREW_DFH_SYSIN_TRAN})"

	jcl=\`jclReplaceDD "\${jcl}" "\${step}" "EQADPFMB" "\${EQAE20_DTCNPROF}"\`
	chk "\$?" "Unable to add DDName EQADPFMB, dataset \${EQAE20_DTCNPROF} to CICS started task \${ZBREW_DFH_PROCLIB}(\${ZBREW_DFH_PROC})"

	procregistrar eqae20 enable \${ZBREW_DFH_PROC} "\${jcl}"
	chk "\$?" "Unable to configure EQAE20"

	#
	# update the startup parameters to enable basic security, if property explicitly set to do so
	# 
	sysin=\`cat "//'\${ZBREW_DFH_SYSIN}(\${ZBREW_DFH_SYSIN_TRAN})'"\`
	if [ "\$ZBREW_DFH_SET_MINIMAL_SECURITY" = "YES" ]; then
		sysin=\`cicsSYSINUpdate "\${sysin}" "SEC" "YES" \`  ; rc1=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XTRAN" "NO"\`  ; rc2=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XCMD" "NO" \`  ; rc3=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XDCT" "NO" \`  ; rc4=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XFCT" "NO" \`  ; rc5=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XHFS" "NO" \`  ; rc6=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XJCT" "NO" \`  ; rc7=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XPPT" "NO" \`  ; rc8=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XPSB" "NO" \`  ; rc9=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XPTKT" "NO"\`  ; rc10=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "XRES" "NO" \`  ; rc11=\$?
		sysin=\`cicsSYSINUpdate "\${sysin}" "GMTRAN" "CESN"\`  ; rc12=\$?
		rc=\`expr \$rc1 + \$rc2 + \$rc3 + \$rc4 + \$rc5 + \$rc6 + \$rc7 + \$rc8 + \$rc9 + \$rc10 + \$rc11 + \$rc12\`
		chk "\$rc" "Unable to change the CICS SYSIN GRPLIST"
	fi

	prefix="*"
	suffix="*"
	hdr="\${prefix} EQAE20 Start \${suffix}"
	ftr="\${prefix} EQAE20 End \${suffix}"
	registrar eqae20 enable \${ZBREW_TGT_HLQ}SYSIN "\${ZBREW_DFH_SYSIN_TRAN}" "\${hdr}" "\${ftr}" "\${prefix}" "\${suffix}" "\${sysin}" 
	chk "\$?" "Unable to update the CICS SYSIN member \${ZBREW_TGT_HLQ}SYSIN \${ZBREW_DFH_SYSIN_TRAN}"

	#
	# Start CICS region with debug enabled
	#
	startCICS "\${ZBREW_DFH_PROC}"
	chk "\$?" "Unable to start CICS region \${ZBREW_DFH_PROC}"

	exit 0
EOF
fi

exit 0
