#!/bin/sh
#
# This should get pulled into the BOM for EQAE20 and general configure from zbrew
#

if ! [ $# -eq 1 ]; then
	echo "Syntax: configregistration <output-script>" >&2
	exit 8
fi
script="$1"
zbrew=`whence zbrew`
zbrewdir=${zbrew%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv
EOF
if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

cat << 'EOF' >>${script}
id="5737-I22"
enablementText="PRODUCT OWNER('IBM CORP')
	NAME('IBM Z OPEN DEV')
	ID(${id})
	VERSION(*) RELEASE(*) MOD(*)
	FEATURENAME('IDz-DEBUGGER')
	STATE(ENABLED)"

swregistrar "eqae20" "enable" "${id}" "${enablementText}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
