#!/bin/sh
#set -x

out=$(whence zbrewfuncs)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
	echo "zbrew tools need to be in your PATH"
	exit 4
fi

mydir=$(callerdir "${0}")
props="${mydir}/../../zbrew/global.properties"
. zbrewprops ${props}


check_CICS(){

fmid_check='y'
ptfs='HCI6900'
chk_prod='CICS Base FMID'
ptf_Check
rc=$?
if [ "${rc}" -eq "17" ]; then
	echo "No PTFs to be checked. FMID not installed in CSI"
else
	ptfs='UW34392 UI61518'
	chk_prod="CICS TS Version 5.2"
	fmid_check='n'
	ptf_Check
fi



}

check_LE(){
case ${release} in
	'02.00' ) ptfs='UI99999 UI30573 UI31702 UI33265 UI43053 UI45429 UI43458 UI49699 UI53511 UI53889 UI54726 UI56507 UI61245 UI29282';;
	'03.00' ) ptfs='UI50167 UI53807 UI53820 UI56511 UI61244';;
	'04.00' ) ptfs='';;
	* ) echo "z/OS 2.${release} not supported for EQAE20";;
esac
chk_prod="Language Environment"
ptf_Check 
}


ptf_Check(){
if [ "${ptfs}" = '' ]; then
	exit 0
fi

if [ "${CHK_CSI}" = "NONE" ]; then
	echo "No SMP/E CSI specified for ${chk_prod}. Pre-requisites are assumed ok"
	exit 0
fi
out=`smpchkptf ${CHK_CSI} ${fmid_check} ${ptfs}`
rc=$?
if [ $rc -gt 0 ]; then
	echo ${out}
else
	echo ${chk_prod}" SMPE check "${out}
fi
return ${rc}
}


zosinfo=`uname -rsvI`
version=`echo ${zosinfo} | awk '{ print $3; }'`
if [ "${version}" != "02" ]; then
	echo "z/OS Version not supported. Must be 02"
	exit 16
fi
release=`echo ${zosinfo} | awk '{ print $2; }'`

CHK_CSI=${CEE_CSI}
fmid_check='n'
check_LE 

CHK_CSI=${CICS_CSI}
check_CICS

# CHK_CSI=$(HLASM_CSI}
# check_HLASM

# CHK_CSI=${COBOL_CSI}
# check_COBOL

exit $rc
