#!/bin/sh

. zbrewsetenv

eqaRoot="${ZBREW_WORKROOT}/deconfig/eqae20"
apfAuthScript="${eqaRoot}/1_apfauth.sh"
regScript="${eqaRoot}/2_swregister.sh"

mkdir -p "${eqaRoot}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "Unable to create de-configuration directory: ${eqaRoot}"
	exit $rc
fi

${mydir}/eqae20configregistration DISABLE ${regScript}
if [ $? -gt 0 ]; then
	exit $?
fi
${mydir}/eqae20configapfauthorization DISABLE ${apfAuthScript}
if [ $? -gt 0 ]; then
	exit $?
fi

exit 0
