#!/bin/sh
#set -x

out=$(whence zbrewfuncs)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
	echo "zbrew tools need to be in your PATH"
	exit 4
fi

mydir=$(callerdir "${0}")
props="${mydir}/../../zbrew/properties/globalprops.json"
zbrewpropse zbrew global ${props}

check_ASM() {
	chk_prod="ASM"
	CHK_CSI=${ASM160_CSI}
	fmid_check='y'
	sysmods='HMQ4160'
	sysmod_Check
	rc=$?
	if [ "${rc}" -eq "16" ]; then
		echo "No PTFs to be checked. FMID not installed in CSI"
	fi
	if [ "${rc}" -eq "0" ]; then
		fmid_check='n'
		sysmods='UK47103 UK59311'
		sysmod_Check
	fi

}


check_IGY(){
	chk_prod="IGY-${igyver}"
	eval CHK_CSI=$"IGY${igyver}_CSI"
	fmid_check='y'
	case ${igyver} in
		510 )
			fmid='HADB510'
			ptfs='UI62769 UI63486 UI63637'
			;;
		520 )
			fmid='HADB520'
			ptfs='UI42823 UI47619 UI62754 UI63478 UI63640'
			;;
		610 )
			fmid='HADB610'
			ptfs='UI43370 UI48286 UI57900'
			;;
		620 )
			fmid='HADB620'
			ptfs='UI57342'
			;;
	esac
	sysmods=${fmid}
	sysmod_Check
	rc=$?
	if [ "${rc}" -eq "16" ]; then
		echo "No PTFs to be checked. Base FMID ${sysmods} is NOT installed in CSI ${CHK_CSI}"
	fi
	if [ "${rc}" -eq 0 ]; then
		fmid_check='n'
		sysmods=${ptfs}
		sysmod_Check
	fi
}



check_DFH(){
	chk_prod="CICS-5.2"
	CHK_CSI=${DFH520_CSI}
	fmid_check='y'
	sysmods='HCI6900'
	sysmod_Check
	rc=$?
	if [ "${rc}" -eq "16" ]; then
		echo "No PTFs to be checked. FMID ${sysmods} is not installed in CSI ${CHK_CSI}"
	fi
	if [ "${rc}" -eq "0" ]; then
		fmid_check='n'
		sysmods='UI22206 UI30410'
		sysmod_Check
	fi

}



check_CEE(){
	chk_prod="LE"
	case ${release} in
		'02.00' ) 
			sysmods='UI30573 UI31702 UI33265 UI43053 UI45429 UI43458 UI49699 UI53511 UI53889 UI54726 UI56507 UI61245 UI29282'
			CHK_CSI=${CEE220_CSI}
			;;
		'03.00' ) 
			sysmods='UI50167 UI53807 UI53820 UI56511 UI61244'
			CHK_CSI=${CEE230_CSI}
			;;
		'04.00' ) 
			sysmods=''
			CHK_CSI=${CEE240_CSI}
			;;
		* ) echo "z/OS 2.${release} not supported for EQAE20";;
	esac
	sysmod_Check 
	
}



sysmod_Check(){
	if [ "${sysmods}" = '' ]; then
		return 0
	fi
	if [ "${CHK_CSI}" = "NONE" ]; then
		echo "No SMP/E CSI specified for ${chk_prod}. Pre-requisites are assumed ok"
		return 0
	fi
	if [ "${fmid_check}" = 'y' ]; then
		out=`smpchkptf ${opts} -f ${CHK_CSI} ${sysmods}`
	else
		out=`smpchkptf ${opts} ${CHK_CSI} ${sysmods}`
	fi
	rc=$?
	if [ $rc -gt 0 ]; then
		echo ${out}
		echo "Missing Pre-requisites .. terminating : ${rc}"
		exit ${rc}
	fi
	return ${rc}
}

debug=0
verbose=0
fmid_check=0
opts=""
while getopts ":vd" opt; do
  case ${opt} in
    d )
      debug=1
      opts="${opts} -d"
      ;;
    v )
      verbose=1
      opts="${opts} -v"
      ;;
    \?)
      if [ ${OPTARG} != "?" ]; then
	msg zbrew ${InvalidOption} E "${OPTARG}"
      fi
      syntax
      exit 4
      ;;
  esac
done


zosinfo=`uname -rsvI`
version=`echo ${zosinfo} | awk '{ print $3; }'`
if [ "${version}" != "02" ]; then
	echo "z/OS Version not supported. Must be 02"
	exit 16
fi
release=`echo ${zosinfo} | awk '{ print $2; }'`

check_CEE 

check_DFH

check_ASM

for igyver in 510 520 610 620; do
	check_IGY
done

exit $rc
