#!/bin/sh
# Need to perform product enablement 

. zbrewsetenv

eqaRoot="${ZBREW_WORKROOT}/config/eqae20"
regScript="${eqaRoot}/1_swregister.sh"
apfAuthScript="${eqaRoot}/2_apfauth.sh"
ivpScript="${eqaRoot}/3_ivp.sh"

mkdir -p "${eqaRoot}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "Unable to create configuration directory: ${eqaRoot}"
	exit $rc
fi

${mydir}/eqae20configregistration ENABLE ${regScript}
if [ $? -gt 0 ]; then
	exit $?
fi
${mydir}/eqae20configapfauthorization ENABLE ${apfAuthScript}
if [ $? -gt 0 ]; then
	exit $?
fi
${mydir}/eqae20configivp ${ivpScript}
if [ $? -gt 0 ]; then
	exit $?
fi

exit 0
