#!/bin/sh

if ! [ $# -eq 1 ]; then
	echo "Syntax: registration <output-script>" >&2
	exit 8
fi
script="$1"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 

cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

cat << 'EOF' >>${script}
# Clean up old SVCs
svclist="EQA00SVC EQA01SVC IGC0014E IGX00051"
for svc in $svclist; do
	mrm "SYS1.LPALIB(${svc})" 2>/dev/null
done

apfregistrar eqae20 enable "${ZBREW_HLQ}EQAE20.SEQAAUTH"
exit $?
EOF

chmod u+x "${script}"
exit 0
