#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: registration ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv ${zbrewroot}

apfregistrar eqae20 "${verb}" "\${ZBREW_HLQ}EQAE20.SEQAAUTH"
exit $?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
