#!/bin/sh
#set -x
. zbrewsetenv

props="${ZBREW_WORKROOT}/order/eqae20order.json"
zbrewpropse eqae20 order "${props}"

eqaRoot="${ZBREW_WORKROOT}/deconfig/eqae20"
mkdir -p "${eqaRoot}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "Unable to create de-configuration directory: ${eqaRoot}"
	exit $rc
fi

cd "${mydir}/generate"
steps=`echo *`
reversesteps=`echo "${steps}" | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }'`
cd $OLDPWD
for step in ${reversesteps}; do
	script="${eqaRoot}/${step}.sh"
	"${mydir}/generate/${step}" DISABLE "${script}"
	if [ $? -gt 0 ]; then
		exit $?
	fi
done

exit 0
