#!/bin/sh

if ! [ $# -eq 1 ]; then
	echo "Syntax: ivp <output-script>" >&2
	exit 8
fi
script="$1"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*} 
zbrewroot=${zbrewdir%/*}

absoluteIVP=`whence eqae20ivp`
cat << EOF >${script}
#!/bin/sh
#set -x
export PATH=${zbrewdir}:\$PATH
. zbrewsetenv ${zbrewroot}

${absoluteIVP} 
exit $?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
